flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class DelPostForm(FlaskForm):
    submit = SubmitField("Delete")

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm, DelPostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    form = DelPostForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        if post.author != current_user and "1" != current_user.get_id():
            abort(403)
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted!', 'success')
        return redirect(url_for('main.home'))
    return render_template('post.html', title=f"Post by {post.author.nickname}", post=post, form=form)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and "1" != current_user.get_id():
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flask_login import login_user, current_user, logout_user
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import LoginForm, RequestResetForm, ResetPasswordForm, UserForm, DeleteUserForm, UpdateUserForm
from flaskblog.users.utils import save_picture, send_reset_email, delete_picture

users = Blueprint('users', __name__)


@users.route("/create_user", methods=['GET', 'POST'])
def create_user():
    if current_user.get_id() != "1":
        abort(403)
    form = UserForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(nickname=form.nickname.data, email=form.email.data, name=form.name.data, password=hashed_password)
        if form.picture.data:
            picture_file = save_picture(form.picture.data, user.name)
            user.image_file = picture_file
        db.session.add(user)
        db.session.commit()
        flash('The account has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_user.html', title='Create a user', form=form, legend="Create a user")


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    names = User.query.with_entities(User.name)
    names = [i[0] for i in names]
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.name.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check name and password', 'danger')
    return render_template('login.html', title='Login', form=form, names=names)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))



@users.route("/user/<string:nickname>", methods=["GET", "POST"])
def user_posts(nickname):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(nickname=nickname).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    form = DeleteUserForm()
    if form.validate_on_submit():
        if current_user.get_id() != "1" or user.id == 1:
            abort(403)
        for post in Post.query.filter_by(author=user):
            db.session.delete(post)
        if user.image_file != "default.jpg":
            delete_picture(user.image_file) 
        db.session.delete(user)
        db.session.commit()
        flash("User was deleted!", "success")
        return redirect(url_for("main.home"))
    return render_template('user_posts.html', posts=posts, user=user, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route("/user/<string:nickname>/update", methods=["GET", "POST"])
def update_user(nickname):
    if current_user.get_id() != "1":
        abort(403)
    user = User.query.filter_by(nickname=nickname).first_or_404()
    form = UpdateUserForm()
    form.user_id.data = str(user.id)
    if form.validate_on_submit():
        user.name = form.name.data
        if form.picture.data:
            if user.image_file != "default.jpg":
                delete_picture(user.image_file)
            picture_file = save_picture(form.picture.data, user.name)
            user.image_file = picture_file
        user.nickname = form.nickname.data
        user.email = form.email.data
        db.session.commit()
        flash("User account was updated!", "success")
        return redirect(url_for("users.user_posts", nickname=user.nickname))
    elif request.method == "GET":
        form.name.data = user.name
        form.nickname.data = user.nickname
        form.email.data = user.email
    return render_template("create_user.html", title="Update " + user.nickname, form=form, legend="Update a user")

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>Общажные мемуары</h1>
    <h5>Сделано по фану</h5>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group mb-3">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/create_user.html
{% extends "layout.html" %} {% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {{form.hidden_tag()}}
  <legend class="border-bottom mb-4">{{legend}}</legend>
  <div class="mb-3">
    {{form.name.label(class="form-label")}} {%if form.name.errors%}
    {{form.name(class="form-control form-control-lg is-invalid")}}
    <div class="invalid-feedback">
      {%for error in form.name.errors%}
      <span>{{error}}</span>
      {%endfor%}
    </div>
    {%else%} {{form.name(class="form-control form-control-lg")}} {%endif%}
  </div>
  <div class="mb-3">
    {{form.nickname.label(class="form-label")}} {%if form.nickname.errors%}
    {{form.nickname(class="form-control form-control-lg is-invalid")}}
    <div class="invalid-feedback">
      {%for error in form.nickname.errors%}
      <span>{{error}}</span>
      {%endfor%}
    </div>
    {%else%} {{form.nickname(class="form-control form-control-lg")}} {%endif%}
  </div>
  <div class="mb-3">
    {{form.email.label(class="form-label")}} {%if form.email.errors%}
    {{form.email(class="form-control form-control-lg is-invalid")}}
    <div class="invalid-feedback">
      {%for error in form.email.errors%}
      <span>{{error}}</span>
      {%endfor%}
    </div>
    {%else%} {{form.email(class="form-control form-control-lg")}} {%endif%}
  </div>
  {%if legend == "Create a user"%}
  <div class="mb-3">
    {{form.password.label(class="form-label")}} {%if form.password.errors%}
    {{form.password(class="form-control form-control-lg is-invalid")}}
    <div class="invalid-feedback">
      {%for error in form.password.errors%}
      <span>{{error}}</span>
      {%endfor%}
    </div>
    {%else%} {{form.password(class="form-control form-control-lg")}} {%endif%}
  </div>
  {%endif%}
  <div class="mb-3">
    {{form.picture.label(class="form-label")}} {%if form.picture.errors%}
    {{form.picture(class="form-control form-control-lg is-invalid")}}
    <div class="invalid-feedback">
      {%for error in form.picture.errors%}
      <span>{{error}}</span>
      {%endfor%}
    </div>
    {%else%} {{form.picture(class="form-control form-control-lg")}} {%endif%}
  </div>
  <div class="mb-3">{{form.submit(class="btn btn-outline-info")}}</div>
</form>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %} {% block content %}
<!-- {% for post in posts.items %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.user_posts', nickname=post.author.nickname) }}"
        >{{ post.author.nickname }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
      <a
        class="text-muted"
        href="{{ url_for('posts.post', post_id=post.id) }}"
      ></a>
    </div>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}  -->
{% for post in posts.items %}
<div class="container pb-3 mb-2 border-top">
  <div class="col">
    <div class="row border-bottom pb-1 pt-1">
      <div class="col-2" style="width: 75px">
        <a
          href="{{ url_for('users.user_posts', nickname=post.author.nickname) }}"
        >
          <img
            src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
            class="img-fluid rounded-circle"
            alt="avatar"
          />
        </a>
      </div>
      <div class="col">
        <div class="d-flex flex-column">
          <h5 class="fw-bold mb-0">{{post.author.nickname}}</h5>
          <div class="m-0">
            <a
              class="text-black"
              href="{{ url_for('posts.post', post_id=post.id) }}"
              >Post</a
            >
            by {{post.author.name}}
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-2 h4 ps-2">{{post.content}}</div>
    <div class="row ps-2">
      <div class="col p-0 text-muted">
        {{ post.date_posted.strftime('%-I:%M %p') }} &#183;
        {{post.date_posted.strftime("%-d %b %Y")}} &#183; Neighbours
      </div>
    </div>
  </div>
</div>
{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}"
  >{{ page_num }}</a
>
{% else %}
<a
  class="btn btn-outline-info mb-4"
  href="{{ url_for('main.home', page=page_num) }}"
  >{{ page_num }}</a
>
{% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />

    {% if title %}
    <title>Neighbours - {{ title }}</title>
    {% else %}
    <title>Neighbours</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
      <div class="container">
        <a class="navbar-brand" href="/">Neighbours</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarToggle"
          aria-controls="navbarToggle"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse container-fluid" id="navbarToggle">
          <div class="navbar-nav">
            <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-link" href="{{ url_for('posts.new_post') }}"
              >New Post</a
            >
            <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
            {%if current_user.get_id() == "1"%}
            <a href="{{url_for('users.create_user')}}" class="nav-link">Create new user</a>
            {%endif%}
          </div>
        </div>
      </div>
    </nav>
    <main role="main" class="container pt-3">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock
          %}
        </div>
      </div>
    </main>

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>
      <div class="input-group mb-3">
        <label for="Selectform" class="input-group-text">{{form.name.label}}</label>
        <select class="form-select" id="Selectform" name="name">
          {%for name in names%}
          <option selected>{{name}}</option>
          {%endfor%}
        </select>
      </div>

      <div class="form-group mb-3">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-check mb-3">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-info me-2") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
      </small>
    </div>
  </form>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %} {% block content %}
<div class="container pb-3 mb-2 border-top">
  <div class="col">
    <div class="row border-bottom pb-1 pt-1">
      <div class="col-2" style="width: 75px">
        <a
          href="{{ url_for('users.user_posts', nickname=post.author.nickname) }}"
        >
          <img
            src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
            class="img-fluid rounded-circle"
            alt="avatar"
          />
        </a>
      </div>
      <div class="col-4">
        <div class="d-flex flex-column">
          <h5 class="fw-bold mb-0">{{post.author.nickname}}</h5>
          <div class="m-0">Post by {{post.author.name}}</div>
        </div>
      </div>
      {% if post.author == current_user or current_user.get_id() == "1" %}
      <div class="col">
        <a
          class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-danger btn-sm m-1"
          data-bs-toggle="modal"
          data-bs-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif %}
    </div>
    <div class="row pt-2 h4 ps-2">{{post.content}}</div>
    <div class="row ps-2">
      <div class="col p-0 text-muted">
        {{ post.date_posted.strftime('%-I:%M %p') }} &#183;
        {{post.date_posted.strftime("%-d %b %Y")}} &#183; Neighbours
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <form
          action=""
          method="POST"
        >
          {{form.hidden_tag()}}
          {{form.submit(class="btn btn-danger")}}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group pb-3">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group pb-3">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group pb-3">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %} {% block content %}
<div class="row mb-3">
  <h2 class="col-12 col-sm-8 col-md-7 col-lg-8">Posts by {{ user.name }}({{ posts.total }})</h2>
  {% if current_user.get_id() == "1" %}
  <div class="col">
    <a
      class="btn btn-secondary btn-sm mt-1 mb-1"
      href="{{ url_for('users.update_user', nickname=user.nickname) }}"
      >Update</a
    >
    <button
      type="button"
      class="btn btn-danger btn-sm m-1"
      data-bs-toggle="modal"
      data-bs-target="#deleteModal"
    >
      Delete
    </button>
  </div>
  {% endif %}
</div>
{% for post in posts.items %}
<div class="container pb-3 mb-2 border-top">
  <div class="col">
    <div class="row border-bottom pb-1 pt-1">
      <div class="col-2" style="width: 75px">
        <a
          href="{{ url_for('users.user_posts', nickname=post.author.nickname) }}"
        >
          <img
            src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
            class="img-fluid rounded-circle"
            alt="avatar"
          />
        </a>
      </div>
      <div class="col-8">
        <div class="d-flex flex-column">
          <h5 class="fw-bold mb-0">{{post.author.nickname}}</h5>
          <div class="m-0">
            <a
              class="text-black"
              href="{{ url_for('posts.post', post_id=post.id) }}"
              >Post</a
            >
            by {{post.author.name}}
          </div>
        </div>
      </div>
    </div>
    <div class="row pt-2 h4 ps-2">{{post.content}}</div>
    <div class="row ps-2">
      <div class="col p-0 text-muted">
        {{ post.date_posted.strftime('%-I:%M %p') }} &#183;
        {{post.date_posted.strftime("%-d %b %Y")}} &#183; Neighbours
      </div>
    </div>
  </div>
</div>

{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
page_num %}
<a
  class="btn btn-info mb-4"
  href="{{ url_for('users.user_posts', nickname=user.nickname, page=page_num) }}"
  >{{ page_num }}</a
>
{% else %}
<a
  class="btn btn-outline-info mb-4"
  href="{{ url_for('users.user_posts', nickname=user.nickname, page=page_num) }}"
  >{{ page_num }}</a
>
{% endif %} {% else %} ... {% endif %} {% endfor %}
<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete User?</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <form action="" method="POST">
          {{form.hidden_tag()}} {{form.submit(class="btn btn-danger")}}
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}